compute_environment: LOCAL_MACHINE
debug: false
distributed_type: FSDP
downcast_bf16: 'no'
enable_cpu_affinity: false
### stable 5.8samples/sec
fsdp_config:
  fsdp_activation_checkpointing: true
  fsdp_backward_prefetch: BACKWARD_PRE
  fsdp_auto_wrap_policy: TRANSFORMER_BASED_WRAP
  fsdp_cpu_ram_efficient_loading: false
  fsdp_offload_params: false
  fsdp_use_orig_params: true
  fsdp_sync_module_states: false
  fsdp_sharding_strategy: SHARD_GRAD_OP
  fsdp_reshard_after_forward: true
  fsdp_state_dict_type: FULL_STATE_DICT
  fsdp_transformer_layer_cls_to_wrap: MotifDecoderLayer
  fsdp_version: 1
main_process_ip: 0.0.0.0 # lo
main_process_port: 8884
main_training_function: main
mixed_precision: bf16
num_machines: 1
num_processes: 8 # test gpu 2
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
