## DeepSeek AITER MLA currently only supports --block-size 1
- benchmark: accuracy
  model: deepseek-ai/DeepSeek-R1-0528 amd/DeepSeek-R1-0528-MXFP4-Preview
  tp: 8
  dtype: auto
  env:
    VLLM_ROCM_USE_AITER: 1
  extra_args:
    --block-size: 1

## gpt-oss requires AITER unified attention and performs best with --block-size 64
## gpt-oss w4a8 is gfx950 only
- benchmark: accuracy
  model: openai/gpt-oss-120b amd/gpt-oss120b-w-mxfp4-a-fp8
  tp: 8
  dtype: auto
  env:
    VLLM_ROCM_USE_AITER: 1
  extra_args:
    --block-size: 64
    --attention-backend: ROCM_AITER_UNIFIED_ATTN
  bench_args:
    --apply_chat_template: True

## For LLama, Mixtral, etc. on gfx942, use float16 for better GEMM perf
- benchmark: accuracy
  model:
    meta-llama/Llama-3.1-405B-Instruct
    amd/Llama-3.1-405B-Instruct-FP8-KV
    meta-llama/Llama-3.3-70B-Instruct
    amd/Llama-3.3-70B-Instruct-FP8-KV
  tp: 8
  dtype: auto
  env:
    VLLM_ROCM_USE_AITER: 1
  extra_args:
    --attention-backend: ROCM_ATTN
  bench_args:
    --apply_chat_template: True
  arch_overrides:
    gfx942:
      dtype: float16

## Llama 3.x MXFP4 (gfx950 only)
- benchmark: accuracy
  model:
    amd/Llama-3.1-405B-Instruct-MXFP4-Preview
    amd/Llama-3.3-70B-Instruct-MXFP4-Preview
  tp: 8
  dtype: auto
  env:
    VLLM_ROCM_USE_AITER: 1
  extra_args:
    --attention-backend: ROCM_ATTN
  bench_args:
    --apply_chat_template: True

- benchmark: accuracy
  model:
    meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8
  tp: 8
  dtype: auto
  env:
    VLLM_ROCM_USE_AITER: 1
  extra_args:
    --attention-backend: ROCM_ATTN
  bench_args:
    --apply_chat_template: True
  arch_overrides:
    gfx942:
      dtype: float16

- benchmark: accuracy
  model:
    mistralai/Mixtral-8x22B-Instruct-v0.1
    amd/Mixtral-8x22B-Instruct-v0.1-FP8-KV
  tp: 8
  dtype: auto
  env:
    VLLM_ROCM_USE_AITER: 1
  extra_args:
    --attention-backend: ROCM_ATTN
  bench_args:
    --apply_chat_template: True
  arch_overrides:
    gfx942:
      dtype: float16

## Qwen 235B requires --enable-expert-parallel with tp 8
- benchmark: accuracy
  model:
    Qwen/Qwen3-235B-A22B-Thinking-2507
    Qwen/Qwen3-235B-A22B-Thinking-2507-FP8
  dtype: auto
  env:
    VLLM_ROCM_USE_AITER: 1
  extra_args:
    --attention-backend: ROCM_ATTN
    --enable-expert-parallel: True
  bench_args:
    --apply_chat_template: True
  arch_overrides:
    gfx942:
      dtype: float16