# 1k 1k mc1
- benchmark: serving
  model:
    openai/gpt-oss-20b
  tp: 1
  inp: 1024
  out: 1024
  dtype: auto
  max_concurrency: 1
  env:
    VLLM_ROCM_USE_AITER: 1
  bench_args:
    --lmeval_apply_chat_template: True

- benchmark: serving
  model:
    meta-llama/Llama-3.1-8B-Instruct
    amd/Llama-3.1-8B-Instruct-FP8-KV
    Qwen/Qwen3-8B
    Qwen/Qwen3-32B
    Qwen/Qwen3-30B-A3B-Thinking-2507
    Qwen/Qwen3-30B-A3B-Thinking-2507-FP8
  tp: 1
  inp: 1024
  out: 1024
  dtype: auto
  max_concurrency: 1
  env:
    VLLM_ROCM_USE_AITER: 1
  arch_overrides:
    gfx942:
      dtype: float16

- benchmark: serving
  model:
    mistralai/Mixtral-8x7B-Instruct-v0.1
    amd/Mixtral-8x7B-Instruct-v0.1-FP8-KV
  tp: 8
  inp: 1024
  out: 1024
  dtype: auto
  max_concurrency: 1
  env:
    VLLM_ROCM_USE_AITER: 1
  arch_overrides:
    gfx942:
      dtype: float16

# Keep Qwen in bf16 on gfx942; Qwen 3.5 exceeds fp16 boundaries and breaks accuracy
- benchmark: serving
  model:
    Qwen/Qwen3-235B-A22B-Thinking-2507
    Qwen/Qwen3-235B-A22B-Thinking-2507-FP8
    Qwen/Qwen3.5-397B-A17B
    Qwen/Qwen3.5-397B-A17B-FP8
  tp: 8
  inp: 1024
  out: 1024
  dtype: auto
  max_concurrency: 1
  env:
    VLLM_ROCM_USE_AITER: 1
  extra_args:
    --enable-expert-parallel: True

- benchmark: serving
  model:
    MiniMaxAI/MiniMax-M2.7
    amd/MiniMax-M2.7-MXFP4
  tp: 4
  inp: 1024
  out: 1024
  dtype: auto
  max_concurrency: 1
  env:
    VLLM_ROCM_USE_AITER: 1
    VLLM_ROCM_SHUFFLE_KV_CACHE_LAYOUT: 1
  extra_args:
    --attention-backend: ROCM_AITER_FA
  arch_overrides:
    gfx942:
      dtype: float16

- benchmark: serving
  model:
    CohereLabs/c4ai-command-r7b-12-2024
  tp: 1
  inp: 1024
  out: 1024
  dtype: auto
  max_concurrency: 1
  env:
    VLLM_ROCM_USE_AITER: 1

- benchmark: serving
  model:
    CohereLabs/command-a-plus-05-2026-bf16
  tp: 8
  inp: 1024
  out: 1024
  dtype: auto
  max_concurrency: 1
  env:
    VLLM_ROCM_USE_AITER: 1
