- benchmark: latency
  model: meta-llama/Llama-3.1-8B-Instruct amd/Llama-3.1-8B-Instruct-FP8-KV
  tp: 1
  inp:  512 
  out: 128
  dtype: auto
  bs: 1 16
  env:
    VLLM_ROCM_USE_AITER: 1
  extra_args:
    --load-format: dummy
  arch_overrides:
    gfx942:
      dtype: float16

- benchmark: throughput
  model: meta-llama/Llama-3.1-8B-Instruct amd/Llama-3.1-8B-Instruct-FP8-KV
  tp: 1
  inp: 128
  out: 128
  dtype: auto
  num_prompts: 10
  env:
    VLLM_ROCM_USE_AITER: 1
  extra_args:
    --load-format: dummy
    --kv-cache-dtype: fp8
  arch_overrides:
    gfx942:
      dtype: float16

- benchmark: serving
  model: meta-llama/Llama-3.1-8B-Instruct amd/Llama-3.1-8B-Instruct-FP8-KV
  tp: 1
  inp: 128
  out: 128
  dtype: auto
  num_prompts: 252
  max_concurrency: 128
  env:
    VLLM_ROCM_USE_AITER: 1
  extra_args:
    --load-format: dummy
  bench_args:
    --random-range-ratio: 0.8
    --lmeval_apply_chat_template: True
  arch_overrides:
    gfx942:
      dtype: float16